AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4

Naming/FileName:
  Exclude:
    - lib/unleash-openfeature-provider.rb

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Max: 160

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 9
